title: "Sebastian Madrazo - Resume"
description: "Professional Resume"
url: "https://smadrazo.github.io"
baseurl: "/resume"

# Personal Information
name: "Sebastian Madrazo"
title_position: "Cloud Architect"
email: "sebastian@madrazo.com.ar"
phone: "+5411 xxxxxx"
location: "Ciudad Autonoma de Buenos Aires"
linkedin: "https://www.linkedin.com/in/sebastianmadrazo/"
github: "github.com/smadrazo"
website: "madrazo.com.ar"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock