title: "Sebastian Madrazo - Resume"
description: "Professional Resume"
url: "https://smadrazo.github.io"
baseurl: "/resume"

# Personal Information
name: "Sebastian Madrazo"
title_position: "Cloud Architect"
email: "your.email@example.com"
phone: "+1 (555) 123-4567"
location: "City, State"
linkedin: "linkedin.com/in/yourprofile"
github: "github.com/yourusername"
website: "yourwebsite.com"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock